language: php

os: linux
dist: xenial

php:
  - 7.2
  - 7.3
  - 7.4

env:
  jobs:
    - DB=mysql

services:
  - mysql

jobs:
  fast_finish: true
  include:
    - php: 7.2
      env: DB=mysql
    
    - php: 7.3
      env: DB=mysql

    - php: 7.4
      env: DB=mysql

before_script:
  - cp config/.env.example config/.env
  - cp config/app_local.example.php config/app_local.php
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE cakephp;'; fi"
  - composer update;
  
script:
   - vendor/bin/phpunit;

notifications:
  email: false