name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
        db-type: [mysql]
        include:
          - php-version: '7.2'
            db-type: 'mysql'
    services:
       mysql:
          image: mysql:5.7
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cakephp
          ports:
            - 3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
    steps:
#    - name: Setup MySQL latest
#      if: matrix.db-type == 'mysql' && matrix.php-version != '7.2'
#     run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cakephp -p 3306:3306 -d mysql --default-authentication-plugin=mysql_native_password --disable-log-bin

    - uses: actions/checkout@v2

    - name: Composer install
      run: | 
          composer update 
          composer install
    - name: arquivos
      run: |
         cp config/.env.example config/.env
         cp config/app_local.example.php config/app_local.php
         
    - name: Run PHPUnit
      run: |       
       if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi
    - name: Submit code coverage
      if: matrix.php-version == '7.4'
      uses: codecov/codecov-action@v1
