name: CI
env:
  MYSQL_DATABASE: cakephp_test
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_HOST: mysql-master

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
      
jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']            
    services:
      mysql-master:
        image: mysql:5.7
      ports:
        - 3306/tcp
      env:
        MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
        MYSQL_USER: ${{ env.MYSQL_USER }}
        MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
      options: >-
        --name=mysql-master
        --health-cmd="mysqladmin ping"
        --health-interval=10s
        --health-timeout=5s
        --health-retries=3
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v1  
      
    - name: Composer install
      run: |
        composer update
        composer install   
    - name: arquivos
      run: |
       cp config/.env.example config/.env
       cp config/app_local.example.php config/app_local.php
    - name: Run PHPUnit
      run: |   
        vendor/bin/phpunit
         
