name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
      
jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
        db-type: [mysql]
        prefer-lowest: ['']
        include:
          - php-version: '7.2'
            db-type: 'mysql'
            prefer-lowest: 'prefer-lowest'
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v1  
      
    - name: Setup MySQL 5.6
      run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cakephp -p 3306:3306 -d mysql:5.6 --character-set-server=utf8
    
    - name: Composer install
      run: |
        composer update --prefer-lowest --prefer-stable
        composer install
        
    - name: run test
      run: |
         vendor/bin/phpunit
