name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
      
jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
        db-type: [mysql]
        prefer-lowest: ['']
        include:
          - php-version: '7.2'
            db-type: 'mysql'
            prefer-lowest: 'prefer-lowest'
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v1  
      
    - name: Setup MySQL 5.6
      run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=secret -e MYSQL_DATABASE=test_myapp -p 3306:3306 -d mysql:5.6 --character-set-server=utf8
    
    - name: Composer install
      run: |
        composer update
        composer install
        
    - name: database config
      run: |
        cp config/.env.example config/.env
        cp config/app_local.example.php config/app_local.php
        
    - name: Run PHPUnit
      run: |   
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} != '7.2' ]]; then export DB_URL='mysql://root:secret@127.0.0.1/test_myapp'; fi
        if [[ ${{ matrix.db-type }} == 'mysql' && ${{ matrix.php-version }} == '7.2' ]]; then export DB_URL='mysql://root:secret@127.0.0.1/test_myapp?encoding=utf8'; fi
        if [[ ${{ matrix.php-version }} == '7.4' ]]; then
          export CODECOVERAGE=1 && vendor/bin/phpunit --verbose --coverage-clover=coverage.xml
        else
          vendor/bin/phpunit
        fi
        
    - name: run test
      run: |
         vendor/bin/phpunit
