name: CI

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
      
jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.2', '7.4']
        db-type: [mysql]
        prefer-lowest: ['']
        include:
          - php-version: '7.2'
            db-type: 'mysql'
            prefer-lowest: 'prefer-lowest'
            
    steps:
    - name: Checkout code
      uses: actions/checkout@v1  
      
    - name: Setup MySQL latest
      run: docker run --rm --name=mysqld -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=cakephp_test -p 3306:3306 -d mysql --default-authentication-plugin=mysql_native_password --disable-log-bin
           
    - name: Composer install
      run: |
        composer update
        composer install
        
    - name: database config
      run: |
        cp config/.env.example config/.env
        cp config/app_local.example.php config/app_local.php
        
    - name: Run PHPUnit
      run: |   
        vendor/bin/phpunit
         
